spring:
  application:
    name: coupon-rush-redis
  profiles:
    active: local   # ??? local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.hibernate.SQL: debug
